_target_: wav2sleep.models.wav2sleep.Wav2Sleep
epoch_mixer:
  _target_: wav2sleep.models.wav2sleep.MultiModalAttentionEmbedder
  activation: gelu
  dim_ff: 512
  dropout: 0.1
  feature_dim: 128
  layers: 2
  nhead: 8
num_classes: 5
sequence_mixer:
  _target_: wav2sleep.models.wav2sleep.SequenceCNN
  activation: gelu
  causal: false
  dropout: 0.1
  feature_dim: 128
  kernel_size: 5
  norm: layer
  num_dilations: 5
  num_layers: 2
signal_encoders:
  _target_: wav2sleep.models.wav2sleep.SignalEncoders
  activation: gelu
  causal: false
  chunk_causal: false
  feature_dim: 128
  initial_channels: 16
  max_channels: 128
  norm: instance
  output_norm: false
  signal_map:
    EOG-L: EOG-L
    EOG-R: EOG-R
  use_residual: true
